[package]
name = "sc-proxy-dex"
version = "0.0.0"
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[features]
wasm-output-mode = [
  "elrond-wasm-node",
  "token_supply/wasm-output-mode",
  "token_merge/wasm-output-mode",
  "nft_deposit/wasm-output-mode",
  "token_send/wasm-output-mode",
]

[dependencies.common_structs]
path = "../../common/common_structs"

[dependencies.elrond_dex_pair]
path = "../../dex/elrond_dex_pair"

[dependencies.elrond_dex_farm]
path = "../../dex/elrond_dex_farm"

[dependencies.sc-locked-asset-factory]
path = "../../sc-locked-asset-factory"

[dependencies.token_supply]
path = "../../common/modules/token_supply"

[dependencies.token_merge]
path = "../../common/modules/token_merge"

[dependencies.nft_deposit]
path = "../../common/modules/nft_deposit"

[dependencies.token_send]
path = "../../common/modules/token_send"

[dependencies.elrond-wasm]
version = "0.18"
features = ["derive"]
path = "../../../elrond-wasm-rs/elrond-wasm"

[dependencies.elrond-wasm-derive]
version = "0.18"
path = "../../../elrond-wasm-rs/elrond-wasm-derive"

[dependencies.elrond-wasm-node]
version = "0.18"
optional = true
path = "../../../elrond-wasm-rs/elrond-wasm-node"

[dev-dependencies.elrond-wasm-debug]
version = "0.18"
path = "../../../elrond-wasm-rs/elrond-wasm-debug"
