[package]
edition = "2018"
name = "sc_distribution_rs"
publish = false
version = "0.0.0"

[lib]
path = "src/lib.rs"

[features]
wasm-output-mode = [
  "elrond-wasm-node",
  "token_supply/wasm-output-mode",
]

[dependencies.common_structs]
path = "../../common/common_structs"

[dependencies.token_supply]
path = "../../common/modules/token_supply"

[dependencies.sc-locked-asset-factory]
path = "../../sc-locked-asset-factory"

[dependencies.elrond-wasm]
version = "0.18"
features = ["derive"]
path = "../../../elrond-wasm-rs/elrond-wasm"

[dependencies.elrond-wasm-derive]
version = "0.18"
path = "../../../elrond-wasm-rs/elrond-wasm-derive"

[dependencies.elrond-wasm-node]
optional = true
version = "0.18"
path = "../../../elrond-wasm-rs/elrond-wasm-node"

[dev-dependencies.elrond-wasm-debug]
version = "0.18"
path = "../../../elrond-wasm-rs/elrond-wasm-debug"
